# Generated by Django 6.1.1 on 2026-10-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Succinct description of what's to be done", max_length=1024)),
                ('description', models.TextField(help_text="Detailed description of what's to be done.")),
                ('test_command', models.TextField(help_text='A shell command for the agent to test with during development.')),
                ('verify_command', models.TextField(blank=True, default='', help_text='A shell command to be run in CI; held back from the dev agent.')),
                ('state', models.CharField(choices=[('open', 'Open'), ('developing', 'Developing'), ('submitted', 'Submitted'), ('verifying', 'Verifying'), ('needs_review', 'Needs review'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket')),
            ],
        ),
    ]
